qod_app/routes/app.py
# -*- coding:utf-8 -*-

"""Quote generator application controllers
"""

from flask import (Blueprint,
                   render_template)

APP_BP = Blueprint('app', __name__)


@APP_BP.route('/')
def home():
    """Returns views to generate a random quote
    """
    return render_template('pages/home.html')


@APP_BP.route('/advanced_search')
def search_quote():
    """Returns views for full text search in quotes database
    """
    return render_template('pages/advanced_search.html')


"""
@APP_BP.route('/suggest_quote', methods=['GET', 'POST'])
def suggest_quote():
    # just for the demo
    # a new quote will be save nowhere here
    if request.method == "POST":
        flash("Thanks for your contributing, please wait until our team check your quote.")
    return render_template('pages/suggest_quote.html')
"""

qod_app/templates/container.html
{% extends 'layout.html' %}
{% block body %}
<!-- header | navbar -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="{{ url_for('app.home') }}">Quote Generator</a>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" href="{{ url_for('app.search_quote') }}">Searching</a>
      </li>
    </ul>
  </div>
</nav>
    {% block content %}{% endblock content %}
{% endblock body %}

qod_app/templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Quote Generator -{%block titre %}{%endblock%}</title>
    {% include "partials/_metadata.html" %}
    {% include "partials/__css_import.html" %}

</head>
<body>
{% block body %}{% endblock body %}
{% block script %}
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
{% endblock script %}
</body>
</html>